### ISSUE TITLE
 v5.0.1 - Cannot read property 'useAppSupportCache' of undefined

### ISSUE THREAD

**Issue by scottpageindysoft** [imjsElectron/electron-differential-updater#18]
**Describe the bug**
Following your example, I added useAppSupportCache: true to package.json, under build.win.publish, but I receive an error "Cannot read property 'useAppSupportCache' of undefined.

**To Reproduce**
Call `await AppUpdater.downloadUpdate` after `update-available` event fires.

**Expected behavior**
`AppUpdater.downloadUpdate` to execute without error

**Screenshots**
https://videos.indysoft.com/DOuxrd1X

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Electron
 - Electron version: 10.0.0-beta.23
 - electron-differential-updater version: 5.0.1

**Additional context**
[Source code I'm using](https://gist.github.com/scottpageindysoft/bfd00bcdb52483794c32175b19dda479)
[Build section of my package.json](https://gist.github.com/scottpageindysoft/69cd34e3de11b7203f1325be12ce92fe)

I was not able to get `download-progress` to work with electron-updater, and I saw a few posts about electron-differential-updater having a fix for that issue.  electron-updater downloads the update, without error, but does not report progress.  electron-differential-updater errors on download, but I can't verify if it does report progress according to the claim.

I poked around in your source code and discovered that `configuration` in `const { configuration } = taskOptions.downloadUpdateOptions.updateInfoAndProvider.provider;` is not checked when it's used `const downloadedUpdateHelper = await this.getOrCreateDownloadHelper(configuration.useAppSupportCache);`;

I don't need or care about `useAppSupportCache`, but I need the update to work without caring if it's there, or not.

I've already lost a week of work due to the horrendous mess that is electron-updater.  Any help would be greatly appreciated.

**Comment by scottpageindysoft** [comment]
Fix that worked for me.
AppUpdater.ts line 720, add `const useAppSupportCache = configuration ? configuration.useAppSupportCache : false;`.
AppUpdater.ts line 721, change to `const downloadedUpdateHelper = await this.getOrCreateDownloadHelper(useAppSupportCache);`.

**Comment by harshitsilly** [comment]
@scottpageindysoft can you try version 4.5.5 without useAppSupportCache option(for now, used by us in internal project)... you will get the progress for differential downloads..
will work on the quick fix..

**Comment by harshitsilly** [comment]
@scottpageindysoft - i know why u are getting the issue.. first of all u should never get configuration undefined.. I think you are running the project in dev mode.. for that electron updater/electron-diiferential-updater will point to dev-app-update.yml . You have to include this file in your root location
`provider: generic
url: http://127.0.0.1:5500/dist
channel: latest
useMultipleRangeRequest: false
useAppSupportCache: true
`

**Comment by harshitsilly** [comment]
issue fixed in PR #23 . Check with version 5.1.0..

**Comment by wartab** [comment]
With version 5.1.0, this problem still occurs.

**Comment by harshitsilly** [comment]
@wartab - can you just send me  your publish options mentioned in package.json

**Comment by wartab** [comment]
We have no publish options, as the defaults all worked with electron-updater. The only thing that was configured is the repository info.

**Comment by akshay-shrivastava** [comment]
@wartab Can you test with the #5.1.2 version

**Comment by wartab** [comment]
Looks like it works fine now.
