### ISSUE TITLE
What is the purpose of this project?

### ISSUE THREAD

**Issue by JonathanLydall** [imjsElectron/electron-differential-updater#28]
As per your description, this project is the same as [electron-updater](https://github.com/electron-userland/electron-builder/tree/master/packages/electron-updater) except it features improved differential update support.

So why did you decide to create a separate project to add these features as opposed to making PRs to add these features directly to `electron-builder` repository?

**Comment by harshitsilly** [comment]
@JonathanLydall - the whole purpose for separating the project is to support the differential update feature on mac for .zip format. We do not want to complicate the electron-updater with this feature for mac.

**Comment by JonathanLydall** [comment]
I feel it's unfortunate you've decided to take the decision to copy the source repo for the following reasons:
- By not using GitHub's fork feature, it's no longer possible to use standard Git tools to see what changes are in your repository compared to the `electron-builder` repository.
- Similarly to the above point, I see it being difficult for you to integrate upstream changes into your own repo, meaning that improvements to the upstream repo are unlikely to be added to yours.

So I feel it's to risky for me to use your project because it has a high risk of becoming incompatible with the upstream project which (at least for the moment) has a lot more momentum behind it.

So I feel said you didn't opt to try PR your features into the upstream repo as a lot of people in my position would have then felt comfortable using your work.

**Comment by harshitsilly** [comment]
@JonathanLydall - in future we can fork the electron-builder repo and move the functionalities there..
