### ISSUE TITLE
Warning printed to console during build with webpack/esbuild

### ISSUE THREAD

**Issue by TomTomB** [imjsElectron/electron-differential-updater#37]
**Describe the bug**
Duing build the following warning will be printed to the console (from esbuild, webppack is similar):

```
node_modules/@imjs/electron-differential-updater/out/generateZipandBlockmap.js:24:20: warning: This call to "require" will not be bundled because the argument is not a string literal (surround with a try/catch to silence this warning)
    24 │ const packageInfo = require(path.join(currentWorkingDirector`...
```

**To Reproduce**
Just try to bundle the package e.g. with esbuild.

**Expected behavior**
No warnings should be printed to the console.

**Desktop (please complete the following information):**
 - OS: Windows 10 (latest build)

**Comment by harshitsilly** [comment]
@TomTomB -  on to this and will update soon.
