### ISSUE TITLE
Differential updater doesn't handle alpha or beta tracks

### ISSUE THREAD

**Issue by ArmelChesnais** [imjsElectron/electron-differential-updater#38]
**Describe the bug**
Differential updater doesn't handle alpha or beta tracks

**To Reproduce**
1. set version to an alpha or beta version of your app (ie: 1.2.3-alpha.4)
2. package the app
2. packaging fails, due to being unable to locate latest-mac.yml file. Only alpha-mac.yml or beta-mac.yml gets generated on an alpha/beta track respectively.

**Expected behavior**
alpha-mac.yml or beta-mac.yml gets loaded according to the current track, instead of always loading latest-mac.yml in every circumstance.

**Screenshots**
N/a

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - Browser N/a
 - Version N/a

**Additional context**
[here is the problematic line](https://github.com/imjsElectron/electron-differential-updater/blob/4b5f45024cf29bd745c684c9ac1e94422196c3f9/src/generateZipandBlockmap.ts#L33), which has "latest-mac.yml" hardcoded in. This should adjust to the current track.
`const ymlPath = path.join(APP_DIST_PATH, "latest-mac.yml");`

**Comment by ArmelChesnais** [comment]
Is there any thoughts on resolving this? It's still relevant for us. I identified the problematic line, but I figured the team for this project would be best at knowing how to implement a solution, as I'm not familiar with the building environment.

**Comment by harshitsilly** [comment]
@ArmelChesnais - not getting enough time.. will try to update u soon with a fix ;)

**Comment by harshitsilly** [comment]
@ArmelChesnais - Issue fixed. Check version 5.1.5
