### ISSUE TITLE
Differential updater uses an app's name and productName inconsistently

### ISSUE THREAD

**Issue by ArmelChesnais** [imjsElectron/electron-differential-updater#48]
**Describe the bug**
Differential updater uses an app's `name` and `productName` inconsistently. It appears to use the app's `productName` on first run for generating the current version's zip cache, whereas when a new version is being compared, it attempts to load the path using the `name` instead

Note: We are using the [electron-react-boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate) as the basis of our app, which uses the two package setup. I however do not believe this affects this issue.

Our package uses "app-desktop" as its name, while it uses "App" as its product name.
When the app starts and the autoupdater is called, it generates the zip cache at `~/Library/Application Support/Caches/App-updater/App-0.1.0-alpha.4-mac.zip`
But then, looking through the updater's log, when an update is found on our servers, and it attempts to compare it to the cached zip, it searches at: `~/Library/Application Support/Caches/app-desktop-updater/App-0.1.0-alpha.4-mac.zip`
(Note the zip's direct parent)

Side note: Our app's user-facing productName has a first letter capitalized as part of our branding, but package.json doesn't accept capitals. Additionally, the package name has "-desktop" appended to differentiate it internally from other platforms we are on. So we cannot match both even as a temporary measure.

**Expected behavior**
The initial config zip cache of the app's path should match the update's comparison path.

**Desktop (please complete the following information):**
 - OS: 10.15.7
 - Browser N/a
 - Version N/a

**Comment by ArmelChesnais** [comment]
I figured I'd also provide our package.json format that exemplifies the different values setup, if that helps:

```JSON
{
  "name": "app-desktop",
  "productName": "App",
  "version": "0.1.0-alpha.4",
  
  "other_values": "...",
  
  "build": {
    "productName": "App",
    "generateUpdatesFilesForAllChannels": true,
    "appId": "com.company.app-desktop",
    
    "other_values": "..."
  }
}
```

**Comment by harshitsilly** [comment]
@ArmelChesnais Problem is I currently do not have mac with me.. ;)
Will patch a fix on a custom branch and will realease a version of module..
U can test that module if  it  wrks fine than we can merge to master + release.

**Comment by ArmelChesnais** [comment]
Sounds good, let me know when it's ready and I'll give it a test.
I would assume it's mostly going to be a question of ensuring the correct name variable is used consistently, though I haven't had time to delve into this. I appreciate you looking into it.

**Comment by harshitsilly** [comment]
@ArmelChesnais  Hey can you try this `yarn add @imjs/electron-differential-updater@5.1.6-beta.1` .. and let me know if it works..

**Comment by ArmelChesnais** [comment]
@harshitsilly Almost, seems to be pulling the right name now consistently, but the current name has `-updater` appended twice.

so it's gone from 
`~/Library/Application Support/Caches/App-updater/App-0.1.0-alpha.4-mac.zip`
and
`~/Library/Application Support/Caches/app-desktop-updater/App-0.1.0-alpha.4-mac.zip`

to:
`~/Library/Application Support/Caches/app-desktop-updater-updater/App-0.1.0-alpha.4-mac.zip`
and
`~/Library/Application Support/Caches/app-desktop-updater/App-0.1.0-alpha.4-mac.zip`

Looks good otherwise, should be ready after the duplicate appending is fixed!

**Comment by harshitsilly** [comment]
Thanks @ArmelChesnais for checking it on ur end.
This should work `yarn add @imjs/electron-differential-updater@5.1.6-beta.2` :)

**Comment by ArmelChesnais** [comment]
Success! All the files appear to be in the right spots, and looked up correctly. Thank you!

**Comment by harshitsilly** [comment]
will soon merge to master and release it..
