### ISSUE TITLE
Electron builder configuration `artifactName` field are not respected. 

### ISSUE THREAD

**Issue by midhuncnair** [imjsElectron/electron-differential-updater#64]
**Describe the bug**
If user configures `artifactName` that should be considered; however, the default is considered.

**To Reproduce**
1. define the `artifactName` field in electron-builder configuration.
2. create the build
3. Observe the output.

**Expected behavior**
the output files should always be in proper format that user configured.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Mac
 - Browser [e.g. chrome, safari]: NA
 - Version [e.g. 22]: 5.1.7

**Comment by harshitsilly** [comment]
@midhuncnair - can you create a PR for all the 3 fixes..
we will be happy to merge the same..

**Comment by midhuncnair** [comment]
@harshitsilly, I have created a PR #65  for all #62 , #63 , and #64.
Please review and let me know if any changes are needed.
